#!/usr/bin/env bash

if [[ -z ${SSH_HOURS} ]]; then
  SSH_HOURS=$1
else
  SSH_HOURS=9
fi

if ! ( which bw > /dev/null ); then
  echo "BitWarden CLI is required."
  echo "try: brew install bitwarden-cli"
  exit 2
fi

TMPFILE1=$(mktemp -t DOWNLOADED_KEY_FILE1)
TMPFILE=$(mktemp -t DOWNLOADED_KEY_FILE)
trap 'rm -f "${TMPFILE}"; rm -f ${TMPFILE1}; echo "deleted temp files"' EXIT

bw logout
echo "logging in"
BW_SESSION=$(bw login phil.goodwin@gmail.com --raw)
LOGIN_STATUS=$?
if [[ ! ( ${LOGIN_STATUS} -eq 0) ]]; then
  echo "login failed"
  exit 1
fi

#BitWarden adds a space to the start of the file for some reason. Use tail to strip it off
bw get notes github_key --session ${BW_SESSION} >> ${TMPFILE1}
bw logout
tail -c +2 ${TMPFILE1} >> ${TMPFILE}
chmod 600 ${TMPFILE}

if [[ ${SSH_HOURS} -eq -1 ]]; then
  ssh-add -q ${TMPFILE} || exit 1
  echo "Key added -- will not expire"
else
  ssh-add -q -t ${SSH_HOURS}H ${TMPFILE} || exit 1
  echo "Key added -- expires in ${SSH_HOURS} hours"
fi
