#!/usr/bin/env bash

if [[ -z ${SSH_HOURS} ]]; then
  SSH_HOURS=$1
else
  SSH_HOURS=9
fi

if ! ( which lpass > /dev/null ); then
  echo "LastPass CLI is required."
  echo "try: brew install lastpass-cli"
  exit 2
fi

lpass status > /dev/null
LPASS_LOGIN_STATUS=$?
if [[ ! ${LPASS_LOGIN_STATUS} -eq 0 ]]; then
  echo "logging in"
  if ! ( lpass login phil.goodwin@gmail.com ); then
    echo "login failed"
    exit 1
  fi
else
  echo "already logged in"
fi

trap 'rm -f "${TMPFILE}"; echo "deleted temp file"' EXIT
TMPFILE=$(mktemp -t DOWNLOADED_KEY_FILE)
lpass show --notes github_key >> ${TMPFILE}

if [[ ! ${LPASS_LOGIN_STATUS} -eq 0 ]]; then
  lpass logout -f
fi

if [[ ${SSH_HOURS} -eq -1 ]]; then
  ssh-add -q ${TMPFILE} || exit 1
  echo "Key added -- will not expire"
else
  ssh-add -q -t ${SSH_HOURS}H ${TMPFILE} || exit 1
  echo "Key added -- expires in ${SSH_HOURS} hours"
fi

# Check whether the key was added to the agent
if ( ssh-add -l | grep -q "${TMPFILE}" ); then
  echo "Key successfully added."
  exit 0
else
  echo "Found passphrase but could not add key."
  exit 1
fi
